package support;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Loads the anonymized real-invoice fixtures in {@code fixtures/reales/}.
 *
 * <p>These are genuine Costa Rica electronic invoices (FE, FC and NC) with all
 * party data pseudonymized and the XAdES signature removed, but with the
 * product data left untouched: real GTIN barcodes, real article descriptions,
 * real commercial units and real discount/tax arithmetic. They exist so parser
 * and upload tests run against realistic input instead of hand-written XML.
 *
 * <p>The v4.3 and v4.4 sets are two views of the same invoices. Every source
 * document in the sample set was v4.3, so the v4.4 set is derived by
 * {@code scripts/derive-facturas-v44.ps1}; each carries its own consecutivo so
 * loading both never trips the parser's duplicate-consecutive guard.
 *
 * <p>Generated by {@code scripts/anonymize-facturas-fixtures.ps1} and verified by
 * {@code scripts/verify-real-fixtures.ps1}. Do not edit the XML by hand.
 */
public final class FacturasReales {

    /** Fixture base names, without the {@code .xml} extension. */
    private static final List<String> NOMBRES = List.of(
            "fe-v43-01", "fe-v43-02", "fe-v43-05", "fe-v43-06", "fe-v43-08",
            "fe-v43-09", "fe-v43-10", "fe-v43-11", "fe-v43-12", "fe-v43-13",
            "fe-v43-14", "fe-v43-15", "fe-v43-16", "fe-v43-17", "fe-v43-18",
            "fc-v43-03",
            "nc-v43-04", "nc-v43-07", "nc-v43-19", "nc-v43-20");

    private static final Pattern CLAVE = Pattern.compile("<Clave>(\\d{50})</Clave>");
    private static final Pattern CONSECUTIVO = Pattern.compile("<NumeroConsecutivo>(\\d{20})</NumeroConsecutivo>");
    private static final Pattern CODIGO_CABYS = Pattern.compile("<CodigoCABYS>(\\d{13})</CodigoCABYS>");
    private static final Pattern CODIGO_V43 = Pattern.compile("<Codigo>(\\d{13})</Codigo>");

    private FacturasReales() {
    }

    /** All fixture base names, canonical v4.3 spelling. */
    public static List<String> nombres() {
        return NOMBRES;
    }

    /**
     * Fixture base names for a schema version, {@code 43} or {@code 44}.
     * The canonical names are the v4.3 ones; the v4.4 set is the same invoices
     * re-derived under the v4.4 schema, so its names are the same with the
     * version segment swapped.
     */
    public static List<String> nombres(String version) {
        return switch (version) {
            case "43" -> NOMBRES;
            case "44" -> NOMBRES.stream().map(n -> n.replace("-v43-", "-v44-")).toList();
            default -> throw new IllegalArgumentException("unknown schema version: " + version);
        };
    }

    /** Fixture base names filtered by document kind: {@code fe}, {@code fc} or {@code nc}. */
    public static List<String> nombres(String version, String kind) {
        return NOMBRES.stream()
                .filter(n -> n.contains("-v" + version + "-"))
                .filter(n -> n.startsWith(kind.toLowerCase() + "-"))
                .toList();
    }

    public static String xml(String nombre) {
        String recurso = "/fixtures/reales/v" + versionDe(nombre) + "/" + nombre + ".xml";
        try (InputStream in = FacturasReales.class.getResourceAsStream(recurso)) {
            if (in == null) {
                throw new IllegalStateException("fixture must be on the test classpath: " + recurso);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("could not read fixture " + recurso, e);
        }
    }

    public static byte[] bytes(String nombre) {
        return xml(nombre).getBytes(StandardCharsets.UTF_8);
    }

    /** The 50-digit Clave of a fixture, as committed. */
    public static String claveDe(String nombre) {
        return primero(CLAVE, xml(nombre), "Clave");
    }

    /** The 20-digit NumeroConsecutivo of a fixture, as committed. */
    public static String consecutivoDe(String nombre) {
        return primero(CONSECUTIVO, xml(nombre), "NumeroConsecutivo");
    }

    /**
     * Returns the fixture with a caller-chipped consecutivo and a Clave rebuilt
     * around it, so a test can import the same real invoice repeatedly without
     * colliding with an earlier import in the same database.
     *
     * <p>The Clave layout is the real one: {@code 506} country, {@code YYMMDD}
     * issue date, the issuer's tax id padded to 12, the 20-digit consecutivo,
     * then 9 digits of security code.
     *
     * @param nombre  fixture base name
     * @param semilla any value that differs between imports of the same fixture
     */
    public static String conConsecutivoUnico(String nombre, int semilla) {
        String xml = xml(nombre);
        String claveOriginal = primero(CLAVE, xml, "Clave");
        String consecutivoOriginal = primero(CONSECUTIVO, xml, "NumeroConsecutivo");

        String consecutivoNuevo = consecutivoOriginal.substring(0, 12)
                + String.format("%08d", digitoSeguro(semilla, 7919L, 999_999L, 700_000L));

        // Clave layout: [0,3) country, [3,9) YYMMDD, [9,21) tax id padded to 12,
        // [21,41) consecutivo, [41,50) security code
        String yymmdd = claveOriginal.substring(3, 9);
        String ruc12 = claveOriginal.substring(9, 21);
        String seguridad = String.format("%09d", digitoSeguro(semilla, 104_729L, 899_999L, 100_000L));
        String claveNueva = "506" + yymmdd + ruc12 + consecutivoNuevo + seguridad;
        assertClave(claveNueva, nombre);

        return xml
                .replace("<NumeroConsecutivo>" + consecutivoOriginal + "</NumeroConsecutivo>",
                        "<NumeroConsecutivo>" + consecutivoNuevo + "</NumeroConsecutivo>")
                .replace("<Clave>" + claveOriginal + "</Clave>",
                        "<Clave>" + claveNueva + "</Clave>");
    }

    /**
     * A non-negative integer in {@code [base, base + rango)} derived from the seed.
     *
     * <p>Computed in {@code long} on purpose: {@code semilla * 104729} overflows
     * {@code int} for any seed above roughly 20,500, and the resulting negative
     * value rendered by {@code String.format("%09d", ...)} puts a minus sign
     * inside the Clave, which the official {@code ClaveType} pattern
     * {@code \d{50,50}} then rejects.
     */
    private static int digitoSeguro(int semilla, long multiplicador, long rango, long base) {
        long mixto = Math.floorMod((long) semilla * multiplicador, rango);
        return (int) (base + mixto);
    }

    /** Fails fast rather than emitting a Clave the Hacienda schema will reject. */
    private static void assertClave(String clave, String nombre) {
        if (clave.length() != 50 || !clave.matches("\\d{50}")) {
            throw new IllegalStateException(
                    "Clave debe ser 50 digitos numericos para " + nombre + ", se genero: " + clave);
        }
    }

    /**
     * Every CAByS code the fixture's line items reference, in document order.
     * v4.4 calls the field {@code CodigoCABYS}; the v4.3 set calls it
     * {@code Codigo}. Seed these as ACTIVO before importing the fixture, or
     * pre-validation will flag them (a warning while the CAByS catalogue is in
     * lenient mode, an error once it is strict).
     */
    public static List<String> codigosCabys(String nombre) {
        String xml = xml(nombre);
        Set<String> codigos = new LinkedHashSet<>();
        Matcher m43 = CODIGO_V43.matcher(xml);
        while (m43.find()) {
            codigos.add(m43.group(1));
        }
        Matcher m44 = CODIGO_CABYS.matcher(xml);
        while (m44.find()) {
            codigos.add(m44.group(1));
        }
        return new ArrayList<>(codigos);
    }

    /** Union of the CAByS codes referenced by every fixture of a version. */
    public static List<String> codigosCabysDeVersion(String version) {
        Set<String> codigos = new LinkedHashSet<>();
        for (String nombre : nombres(version)) {
            codigos.addAll(codigosCabys(nombre));
        }
        return new ArrayList<>(codigos);
    }

    /** Fixture name carries the version as {@code -v43-} but the folder is {@code v4.3}. */
    private static String versionDe(String nombre) {
        int i = nombre.indexOf("-v");
        if (i < 0 || i + 4 >= nombre.length()) {
            throw new IllegalArgumentException("fixture name must carry a version: " + nombre);
        }
        String version = nombre.substring(i + 2, i + 4);
        return version.charAt(0) + "." + version.charAt(1);
    }

    private static String primero(Pattern patron, String xml, String que) {
        Matcher m = patron.matcher(xml);
        if (!m.find()) {
            throw new IllegalStateException("fixture has no " + que);
        }
        return m.group(1);
    }
}
