package Services;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.XMLConstants;
import javax.xml.transform.Source;
import org.xml.sax.SAXException;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;
import org.w3c.dom.ls.LSInput;
import org.w3c.dom.ls.LSResourceResolver;

/**
 * Pre-submission XSD validation for Hacienda electronic documents (v4.4).
 * <p>
 * Loads the official Hacienda XSD schemas from classpath resources and validates
 * a marshalled XML document <em>before</em> it is signed and submitted to MH.
 * Catches structural errors (missing required elements, wrong types, out-of-range
 * values) early instead of getting a cryptic MH rejection.
 * </p>
 * <p>Supported document types:</p>
 * <ul>
 *   <li>FE  - Factura Electr&oacute;nica</li>
 *   <li>TE  - Tiquete Electr&oacute;nico</li>
 *   <li>NC  - Nota de Cr&eacute;dito Electr&oacute;nica</li>
 *   <li>ND  - Nota de D&eacute;bito Electr&oacute;nica</li>
 *   <li>FEC - Factura Electr&oacute;nica de Compra</li>
 *   <li>FEE - Factura Electr&oacute;nica de Exportaci&oacute;n</li>
 *   <li>REP - Recibo Electr&oacute;nico de Pago</li>
 * </ul>
 */
@jakarta.inject.Named
@jakarta.enterprise.context.ApplicationScoped
public class HaciendaXsdValidator {

    private static final Logger LOG = Logger.getLogger(HaciendaXsdValidator.class.getName());

    // Namespaces must match the XML generated by the JAXB models
    static final String FE_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica";
    static final String TE_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/tiqueteElectronico";
    static final String NC_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaCreditoElectronica";
    static final String ND_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/notaDebitoElectronica";
    static final String FEC_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronicaCompra";
    static final String FEE_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronicaExportacion";
    static final String REP_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/reciboElectronicoPago";
    static final String MR_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeReceptor";
    static final String MH_NS =
        "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda";

    // Schema instances are created lazily and cached
    private volatile Schema feSchema;
    private volatile Schema teSchema;
    private volatile Schema ncSchema;
    private volatile Schema ndSchema;
    private volatile Schema fecSchema;
    private volatile Schema feeSchema;
    private volatile Schema repSchema;
    private volatile Schema mrSchema;
    private volatile Schema mhSchema;

    // ── Resource resolver ──────────────────────────────────────────────────

    /**
     * Resolves the {@code ../../xmldsig-core-schema.xsd} import that the
     * Hacienda XSDs declare, by loading the resource from the classpath.
     */
    private static class ClasspathResourceResolver implements LSResourceResolver {
        @Override
        public LSInput resolveResource(final String type,
                                       final String namespaceURI,
                                       final String publicId,
                                       final String systemId,
                                       final String baseURI) {
            // Intercept the xmldsig import — handle both the relative path and bare filename
            if (systemId != null && systemId.contains("xmldsig-core-schema.xsd")) {
                InputStream is = HaciendaXsdValidator.class
                    .getResourceAsStream("/xsd/xmldsig-core-schema.xsd");
                if (is != null) {
                    return new SimpleLSInput(publicId, systemId, is);
                }
                LOG.warning("xmldsig-core-schema.xsd not found on classpath");
            }
            return null; // fall back to default resolution
        }
    }

    /**
     * Minimal LSInput implementation backed by a byte-stream.
     */
    private static class SimpleLSInput implements LSInput {
        private final String publicId;
        private final String systemId;
        private final InputStream inputStream;

        SimpleLSInput(final String publicId, final String systemId,
                      final InputStream inputStream) {
            this.publicId = publicId;
            this.systemId = systemId;
            this.inputStream = inputStream;
        }

        @Override public Reader getCharacterStream() { return null; }
        @Override public void setCharacterStream(final Reader characterStream) { }
        @Override public InputStream getByteStream() { return inputStream; }
        @Override public void setByteStream(final InputStream byteStream) { }
        @Override public String getStringData() { return null; }
        @Override public void setStringData(final String stringData) { }
        @Override public String getSystemId() { return systemId; }
        @Override public void setSystemId(final String systemId) { }
        @Override public String getPublicId() { return publicId; }
        @Override public void setPublicId(final String publicId) { }
        @Override public String getBaseURI() { return null; }
        @Override public void setBaseURI(final String baseURI) { }
        @Override public String getEncoding() { return null; }
        @Override public void setEncoding(final String encoding) { }
        @Override public boolean getCertifiedText() { return false; }
        @Override public void setCertifiedText(final boolean certifiedText) { }
    }

    // ── Schema factory ────────────────────────────────────────────────────

    private Schema createSchema(final String classpathResource) {
        try {
            SchemaFactory factory =
                SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
            factory.setResourceResolver(new ClasspathResourceResolver());

            final InputStream xsdIs = getClass().getResourceAsStream(classpathResource);
            if (xsdIs == null) {
                throw new RuntimeException("XSD resource not found: " + classpathResource);
            }

            final StreamSource source = new StreamSource(xsdIs);
            // Set system-id so relative imports (../../xmldsig-core-schema.xsd)
            // can be resolved by our custom LSResourceResolver against the base URI.
            final java.net.URL resourceUrl = getClass().getResource(classpathResource);
            if (resourceUrl != null) {
                source.setSystemId(resourceUrl.toString());
            }

            return factory.newSchema(source);
        } catch (SAXException | RuntimeException e) {
            LOG.log(Level.SEVERE, "Failed to compile XSD schema from " + classpathResource, e);
            return null;
        }
    }

    private Schema getFeSchema() {
        if (feSchema == null) {
            synchronized (this) {
                if (feSchema == null) {
                    feSchema = createSchema("/xsd/v4.4/FacturaElectronica_V4.4.xsd");
                }
            }
        }
        return feSchema;
    }

    private Schema getTeSchema() {
        if (teSchema == null) {
            synchronized (this) {
                if (teSchema == null) {
                    teSchema = createSchema("/xsd/v4.4/TiqueteElectronico_V4.4.xsd");
                }
            }
        }
        return teSchema;
    }

    private Schema getNcSchema() {
        if (ncSchema == null) {
            synchronized (this) {
                if (ncSchema == null) {
                    ncSchema = createSchema("/xsd/v4.4/NotaCreditoElectronica_V4.4.xsd");
                }
            }
        }
        return ncSchema;
    }

    private Schema getNdSchema() {
        if (ndSchema == null) {
            synchronized (this) {
                if (ndSchema == null) {
                    ndSchema = createSchema("/xsd/v4.4/NotaDebitoElectronica_V4.4.xsd");
                }
            }
        }
        return ndSchema;
    }

    private Schema getFecSchema() {
        if (fecSchema == null) {
            synchronized (this) {
                if (fecSchema == null) {
                    fecSchema = createSchema("/xsd/v4.4/FacturaElectronicaCompra_V4.4.xsd");
                }
            }
        }
        return fecSchema;
    }

    private Schema getFeeSchema() {
        if (feeSchema == null) {
            synchronized (this) {
                if (feeSchema == null) {
                    feeSchema = createSchema("/xsd/v4.4/FacturaElectronicaExportacion_V4.4.xsd");
                }
            }
        }
        return feeSchema;
    }

    private Schema getRepSchema() {
        if (repSchema == null) {
            synchronized (this) {
                if (repSchema == null) {
                    repSchema = createSchema("/xsd/v4.4/ReciboElectronicoPago_V4.4.xsd");
                }
            }
        }
        return repSchema;
    }

    private Schema getMrSchema() {
        if (mrSchema == null) {
            synchronized (this) {
                if (mrSchema == null) {
                    mrSchema = createSchema("/xsd/v4.4/MensajeReceptor_V4.4.xsd");
                }
            }
        }
        return mrSchema;
    }

    private Schema getMhSchema() {
        if (mhSchema == null) {
            synchronized (this) {
                if (mhSchema == null) {
                    mhSchema = createSchema("/xsd/v4.4/MensajeHacienda_V4.4.xsd");
                }
            }
        }
        return mhSchema;
    }

    // ── Public API ─────────────────────────────────────────────────────────

    /** Outcome of an XSD validation check. */
    public static final class ValidationResult {
        public final boolean valid;
        public final String errorMessage;

        private ValidationResult(final boolean valid, final String errorMessage) {
            this.valid = valid;
            this.errorMessage = errorMessage;
        }

        public static ValidationResult ok() {
            return new ValidationResult(true, null);
        }

        public static ValidationResult error(final String message) {
            return new ValidationResult(false, message);
        }
    }

    /**
     * Validate {@code xml} against the schema identified by its root-element
     * namespace.
     *
     * @param xml       the marshalled XML document as a string.
     * @param namespace the target namespace of the document (determines which
     *                  schema is used).
     * @return {@link ValidationResult#ok() ok} if valid,
     *         {@link ValidationResult#error error} with a description otherwise.
     */
    public ValidationResult validate(final String xml, final String namespace) {
        final Schema schema;
        if (FE_NS.equals(namespace)) {
            schema = getFeSchema();
        } else if (TE_NS.equals(namespace)) {
            schema = getTeSchema();
        } else if (NC_NS.equals(namespace)) {
            schema = getNcSchema();
        } else if (ND_NS.equals(namespace)) {
            schema = getNdSchema();
        } else if (FEC_NS.equals(namespace)) {
            schema = getFecSchema();
        } else if (FEE_NS.equals(namespace)) {
            schema = getFeeSchema();
        } else if (REP_NS.equals(namespace)) {
            schema = getRepSchema();
        } else if (MR_NS.equals(namespace)) {
            schema = getMrSchema();
        } else if (MH_NS.equals(namespace)) {
            schema = getMhSchema();
        } else {
            return ValidationResult.error("Unknown document namespace: " + namespace);
        }

        if (schema == null) {
            return ValidationResult.error(
                "XSD schema could not be loaded — validation unavailable");
        }

        try {
            final Validator validator = schema.newValidator();
            validator.validate(
                new StreamSource(new ByteArrayInputStream(xml.getBytes("UTF-8"))));
            return ValidationResult.ok();
        } catch (SAXException | IOException | RuntimeException e) {
            return ValidationResult.error("XSD validation failed: " + e.getMessage());
        }
    }
}
